service: StatsService
frameworkVersion: '3'

plugins:
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-2

functions:
  createSession:
    handler: src/endpoints/sessions/createSession/handler.handler
    events:
      - httpApi:
          path: /courses/{courseId}
          method: post

  getCourseLifetimeStats:
    handler: src/endpoints/sessions/getCourseLifetimeStats/handler.handler
    events:
      - httpApi:
          path: /courses/{courseId}
          method: get

  getSession:
    handler: src/endpoints/sessions/getSession/handler.handler
    events:
      - httpApi:
          path: /courses/{courseId}/sessions/{sessionId}
          method: get

resources:
  Resources:
    Sessions:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Sessions
        AttributeDefinitions:
          - AttributeName: hashKey
            AttributeType: S
          - AttributeName: sortKey
            AttributeType: S
        KeySchema:
          - AttributeName: hashKey
            KeyType: HASH
          - AttributeName: sortKey
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1